export const colorList = {
  cardBoxShadow: "#d5d6dc",
  cardBoxShadowHover: "#aeaeae",
  cardBackground: "#f3f4f7",
  colorAddButton: "#dc7777",
  levelTubeBackground: "#e4e4e4",
  levelTubeBoxShadow: "#d4d4d4",
  levelTubeValueBackground: "#f3701a",
  bottomBarBackground: "#ec5656",
  bottomBarBoxShadow: "d9333387",
  bottomBarTextColor: "#ffffff",
  modalOutside: "#000000a3",
  modalContentBoxShadow: "#474444",
  modalContentBackground: "#ffffff",
  searchBoxBorder: "#e6e6e6",
}